services:
  - type: web
    name: thht-crm
    runtime: node
    repo: https://github.com/williamstronghtth/thht-crm
    branch: master
    buildCommand: npm install
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
