#!/bin/bash
# Fix withdrawn figures in published blog posts using curl

CREDS="chris@cbcoastrealty.com:Au1M DJEn iU9X 7YSh m7am nPSA"
WP_URL="https://thehooverhometeam.com"

echo "🔧 Fixing withdrawn figures in blog posts...\n"

# Fix Post 49569 - remove "6.8% or higher" and "7 days on market"
echo "📝 Fixing post 49569..."
curl -s -X POST "$WP_URL/wp-json/wp/v2/posts/49569" \
  -u "$CREDS" \
  -H "Content-Type: application/json" \
  -d '{
    "content": "<p>August is the busiest relocation month in the Northeast. Families are moving for back-to-school, job transfers, and new beginnings. And if you'\''re relocating to Southern New Hampshire, the timing is more than right. Here'\''s why August real estate opportunities in Southern NH are at their peak.</p>\n<h2>The Rate Environment: Why 6.65–6.77% Matters</h2>\n<p>Mortgage rates are holding steady around 6.65 to 6.77 percent. That'\''s not the 7-plus percent many feared earlier in 2026. If you'\''re planning to relocate, your rate-lock window is important.</p>\n<p>A locked-in rate of 6.65 to 6.77 percent protects you from higher borrowing costs in the fall and winter. That certainty matters when you'\''re making a major life decision like moving to a new state.</p>\n<h2>August Is Peak Relocation Season</h2>\n<p>August is the single busiest relocation month in the Northeast. Families are moving for back-to-school, corporate transfers, and lifestyle changes. The market is active, inventory is moving, and buyers have urgency. Sellers know this too, which means your offers are taken seriously. You'\''re negotiating from a position of intent, not desperation.</p>\n<h2>Inventory Is Climbing, Competition Is Falling</h2>\n<p>The Southern New Hampshire real estate market has shifted. After two years of razor-thin inventory and multiple-offer bidding wars, new listings are climbing. Homes in Hillsborough County are moving quickly, but you'\''re no longer competing in a frenzy.</p>\n<p>This is the moment when your offers have power. Sellers are more flexible. Appraisals are more likely to support your purchase price. You have breathing room to negotiate terms, closing timelines, and contingencies.</p>\n<h2>What This Means for You</h2>\n<p>If you'\''re relocating from Boston, New York, or another high-cost area, Southern New Hampshire offers something rare: stable rates, growing inventory, and less competition. Your dollar goes further. Your commute is reasonable (45 to 60 minutes to Boston suburbs). The schools are strong. The quality of life is exceptional.</p>\n<p>August is your launch window. Lock in your rate. Make your move. Contact us to explore the homes and neighborhoods that fit your family'\''s needs.</p>"
  }' | jq '.id, .modified' && echo "✅ Post 49569 fixed\n"

# Fix Post 49572 - replace "1.4 months" with more general language
echo "📝 Fixing post 49572..."
curl -s -X POST "$WP_URL/wp-json/wp/v2/posts/49572" \
  -u "$CREDS" \
  -H "Content-Type: application/json" \
  -d '{
    "content": "<p>Nashua just got ranked America'\''s hottest housing market. If you'\''re buying, the truth is more nuanced than the headline. Here'\''s what the data actually means for buyers in Hillsborough County.</p>\n<h2>Why Nashua Is Ranked America'\''s Hottest Market</h2>\n<p>The &#8220;hottest market&#8221; designation typically refers to demand velocity, inventory turnover, and price momentum. Nashua checks all those boxes. Homes are selling fast. Prices are appreciating. Buyers are active. But &#8220;hot market&#8221; has a different meaning depending on your budget.</p>\n<h2>The Reality for Buyers Under $500K</h2>\n<p>In Nashua, homes under $500,000 are still seeing multiple offers. The market is tight at the entry level. If you'\''re looking for a starter home or a rental investment, you'\''re competing hard. Appraisals sometimes lag offer prices. Contingencies are limited. The buying experience is still seller-favorable in this price band.</p>\n<h2>The Opportunity Zone: $500K to $900K</h2>\n<p>This is where the market shifts. In the $500,000 to $900,000 range, where most families land, Amherst, Hollis, and Bow are seeing real negotiating room. Inventory levels are improving across the region, which means real movement and more options for buyers. Buyers in this band have options, can inspect homes thoroughly, and can negotiate terms.</p>\n<p>If you'\''re buying a family home or an upgrade, this is your sweet spot right now. The market is balanced enough for realistic negotiating, and homes are moving quickly.</p>\n<h2>What Improving Inventory Means</h2>\n<p>Balanced markets typically have 5 to 6 months of inventory. In a buyer'\''s market, inventory climbs to 8 to 12 months. Hillsborough County is still seller-favorable, but it'\''s rebalancing. Homes aren'\''t sitting on market for months. But there are more homes to choose from, and buyers have time to make decisions.</p>\n<h2>Your Next Move</h2>\n<p>If you'\''re buying in the $500K to $900K range, now is the time. You have inventory to browse, terms to negotiate, and rates locked in the mid-6% range. The opportunity window is real, and it'\''s open right now. Let'\''s explore what'\''s available in your target neighborhoods.</p>"
  }' | jq '.id, .modified' && echo "✅ Post 49572 fixed\n"

# Fix Post 49575 - replace "7-day" metrics with "strong velocity"
echo "📝 Fixing post 49575..."
curl -s -X POST "$WP_URL/wp-json/wp/v2/posts/49575" \
  -u "$CREDS" \
  -H "Content-Type: application/json" \
  -d '{
    "content": "<p>Homes are selling with strong velocity right now in Southern New Hampshire. That pace is real, and it won'\''t last forever. Here'\''s why sellers should list before October.</p>\n<h2>What Strong Sales Velocity Tells Us</h2>\n<p>When homes in Hillsborough County are selling quickly, it means buyer intent is high. Homes are showing strong. The market is moving fast. If your home is listed during this window, it'\''s in front of active, motivated buyers who are ready to make decisions quickly.</p>\n<h2>Q4 Is Slower—Much Slower</h2>\n<p>October through December is a different market. Thanksgiving, Christmas, and year-end holidays mean fewer showings. Fewer competing homes means fewer buyers see your listing. Work-from-home arrangements mean less relocation urgency. Sellers who are house-hunting slower, and the pool of available homes shrinks faster than the pool of buyers.</p>\n<p>Q4 isn'\''t a bad time to sell, but it'\''s a slower time. And slower means less visibility and less urgency from your buyer pool.</p>\n<h2>Peak-Exposure Window: August and September</h2>\n<p>August and September are the peak-exposure window for sellers. Back-to-school drives relocation. Job transitions happen in late summer. Families want to settle before the holidays. The buyer pool is large, motivated, and shopping actively. Your home gets seen by the right audience at the right time.</p>\n<h2>The Advantage of Listing Now</h2>\n<p>If you'\''re thinking about selling in 2026, August and September are your golden window. Your home will be shown to active, motivated buyers. Your sales timeline will be fast. Your negotiating position will be strong. You'\''ll close before the holidays and avoid the Q4 slowdown entirely.</p>\n<p>Once October rolls around, the market shifts. You'\''ll still sell, but it will take longer, attract fewer competing offers, and face more seasonal headwinds. The advantage of listing now is very real.</p>\n<h2>Let'\''s Discuss Your Timeline</h2>\n<p>If you'\''re considering selling this year, now is the moment to have a conversation. Market conditions are favorable. Buyer intent is high. The window is open. Let'\''s discuss your home, your timeline, and your goals. The timing is right.</p>"
  }' | jq '.id, .modified' && echo "✅ Post 49575 fixed\n"

echo "✅ All blog posts have been corrected!"
