"""
models/game/predictor.py — High-level game prediction orchestrator.

This module ties everything together: it takes a game (two teams, a venue,
a ref crew) and produces actionable predictions by:

1. Loading all sub-models (coach, player, referee)
2. Gathering relevant data for both teams
3. Running the game simulator
4. Translating simulation results into betting signals

This is the main entry point for "predict today's games."
"""

import logging
from dataclasses import dataclass, field
from datetime import date

import pandas as pd

from models.game.simulator import GameSimulator, SimulationSummary

logger = logging.getLogger(__name__)


@dataclass
class GamePrediction:
    """Complete prediction for a single NBA game."""
    game_id: str = ""
    game_date: str = ""
    home_team: str = ""
    away_team: str = ""
    home_team_id: int = 0
    away_team_id: int = 0
    # Core predictions
    home_win_prob: float = 0.5
    predicted_home_score: float = 0.0
    predicted_away_score: float = 0.0
    predicted_total: float = 0.0
    predicted_spread: float = 0.0  # home perspective
    # Model components
    coach_adjustment: float = 0.0   # coach model contribution
    matchup_adjustment: float = 0.0 # matchup model contribution
    referee_adjustment: float = 0.0 # referee model contribution
    # Confidence
    confidence: float = 0.0  # 0-1, based on model agreement and data quality
    simulation_std: float = 0.0
    # Betting signals
    signals: list = field(default_factory=list)  # list of BetSignal dicts
    # Raw simulation
    simulation_summary: SimulationSummary | None = None


@dataclass
class BetSignal:
    """A specific betting signal generated by the model."""
    bet_type: str = ""      # "spread", "total", "moneyline"
    side: str = ""          # "home", "away", "over", "under"
    line: float = 0.0       # the line/total
    model_prob: float = 0.0 # our estimated probability
    edge: float = 0.0       # model_prob - implied_prob (from odds)
    confidence: str = ""    # "low", "medium", "high"
    reasoning: str = ""     # human-readable explanation


class GamePredictor:
    """
    Orchestrate game predictions using all sub-models.

    Usage:
        predictor = GamePredictor()
        predictor.load_models(season="2024-25")
        predictions = predictor.predict_games(game_date=date.today())
    """

    def __init__(self, n_simulations: int = 10000):
        self.n_simulations = n_simulations
        self.simulator = GameSimulator()
        # Sub-models (loaded via load_models)
        self.rotation_model = None
        self.foul_trouble_model = None
        self.timeout_model = None
        self.per_possession_model = None
        self.chemistry_model = None
        self.matchup_model = None
        self.foul_rate_model = None
        self.home_bias_model = None
        self.late_game_model = None

    def load_models(self, season: str = "2024-25") -> None:
        """
        Load all trained sub-models for a season.

        TODO:
        1. Load serialized models from data/models/{season}/
        2. Or train from scratch if not cached:
           a. Load processed data from data/processed/{season}/
           b. Train each sub-model
           c. Cache for future use
        """
        logger.info("Loading models for season %s ...", season)

        # TODO: Implement model loading/training
        # For initial version, models train on the fly from processed data
        # Later: serialize with pickle/joblib for fast loading

    def predict_game(self, home_team_id: int, away_team_id: int,
                     crew_ids: list[int] = None,
                     injuries: dict = None) -> GamePrediction:
        """
        Generate a complete prediction for a single game.

        TODO:
        1. Gather team data:
           - Roster, recent form (last 10 games)
           - Coach profile
           - Home/away splits
        2. Apply sub-model adjustments:
           a. Coach rotation → expected lineup quality curve
           b. Player per-possession → baseline ratings
           c. Chemistry → lineup interaction adjustments
           d. Matchups → opponent-specific adjustments
           e. Referee → foul/pace/bias adjustments
        3. Configure simulator with all adjustments
        4. Run N simulations
        5. Generate betting signals from distribution

        Parameters
        ----------
        home_team_id : int
            NBA team ID for home team.
        away_team_id : int
            NBA team ID for away team.
        crew_ids : list[int]
            Referee crew IDs (if known).
        injuries : dict
            {team_id: [player_ids]} of injured/out players.

        Returns
        -------
        GamePrediction
            Complete prediction with signals.
        """
        logger.info("Predicting game: %d (home) vs %d (away)", home_team_id, away_team_id)

        # Configure simulator
        self.simulator.configure(
            home_team_id=home_team_id,
            away_team_id=away_team_id,
            crew_ids=crew_ids or [],
            rotation_model=self.rotation_model,
            player_model=self.per_possession_model,
            chemistry_model=self.chemistry_model,
            matchup_model=self.matchup_model,
            referee_model=self.foul_rate_model,
        )

        # Run simulation
        summary = self.simulator.run(n_simulations=self.n_simulations)

        prediction = GamePrediction(
            home_team_id=home_team_id,
            away_team_id=away_team_id,
            home_win_prob=summary.home_win_pct,
            predicted_home_score=summary.avg_home_score,
            predicted_away_score=summary.avg_away_score,
            predicted_total=summary.avg_total,
            predicted_spread=summary.avg_spread,
            simulation_std=summary.std_total,
            simulation_summary=summary,
        )

        return prediction

    def predict_games(self, game_date: date = None,
                      season: str = "2024-25") -> list[GamePrediction]:
        """
        Predict all games on a given date.

        TODO:
        1. Get today's schedule from processed game data or API
        2. Get injury reports (manual input or scraping)
        3. Get referee assignments (usually released day of game)
        4. Run predict_game for each matchup
        5. Generate betting signals with edge calculations

        Parameters
        ----------
        game_date : date
            Date to predict for. Defaults to today.
        season : str
            NBA season string.

        Returns
        -------
        list[GamePrediction]
            Predictions for all games on the date.
        """
        if game_date is None:
            game_date = date.today()

        logger.info("Predicting games for %s", game_date)

        # TODO: Implement daily prediction pipeline
        # 1. Fetch today's schedule
        # 2. Loop through games
        # 3. Generate predictions

        predictions = []
        return predictions

    def generate_signals(self, prediction: GamePrediction,
                         market_odds: dict = None) -> list[dict]:
        """
        Generate betting signals by comparing model to market.

        TODO:
        1. For spread: compare model spread to market spread
        2. For total: compare model total to market over/under
        3. For moneyline: compare model win prob to implied odds
        4. Calculate edge (model_prob - implied_prob)
        5. Filter to signals with edge > threshold (e.g., 3%)
        6. Assign confidence based on edge size and model agreement

        Parameters
        ----------
        prediction : GamePrediction
            Our model's prediction.
        market_odds : dict
            Market lines, e.g.:
            {"spread": -3.5, "total": 224.5, "home_ml": -150, "away_ml": +130}
        """
        if market_odds is None:
            return []

        signals = []

        # TODO: Implement signal generation
        # Compare simulation distribution to market lines
        # e.g., if we think home covers 55% but market implies 50%, that's an edge

        return signals
